export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_USERS = 'FETCH_USERS';
export const SET_GITHUB_USERS = 'SET_GITHUB_USERS';
export const FETCH_USERSET_REPOSITORIES = 'FETCH_USERSET_REPOSITORIES';
export const SET_USER_REPOSITORIES = 'SET_USER_REPOSITORIES';
