export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_USERS = 'FETCH_USERS';
export const SET_GITHUB_USERS = 'SET_GITHUB_USERS';
export const FETCH_USER_REPOSITORIES = 'FETCH_USERS_REPOSITORIES';
export const FETCH_USER_GISTS = 'FETCH_USER_GISTS';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAN_USER_DATA = 'CLEAN_USER_DATA';
