export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_USERS = 'FETCH_USERS';
export const SET_GITHUB_USERS = 'SET_GITHUB_USERS';
export const FETCH_USER_REPOSITORIES = 'FETCH_USERS_REPOSITORIES';
export const SET_USER_REPOSITORIES = 'SET_USER_REPOSITORIES';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAN_USER_REPOSITORIES = 'CLEAN_USER_REPOSITORIES';
